// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SampleRecommendation.ConsoleApp
{
    public partial class SampleRecommendation
    {
        /// <summary>
        /// model input class for SampleRecommendation.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"User")]
            public float User { get; set; }

            [ColumnName(@"Review #")]
            public float Review__ { get; set; }

            [ColumnName(@"Brand")]
            public string Brand { get; set; }

            [ColumnName(@"Variety")]
            public string Variety { get; set; }

            [ColumnName(@"Style")]
            public string Style { get; set; }

            [ColumnName(@"Country")]
            public string Country { get; set; }

            [ColumnName(@"Stars")]
            public float Stars { get; set; }

            [ColumnName(@"Top Ten")]
            public string Top_Ten { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SampleRecommendation.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"User")]
            public uint User { get; set; }

            [ColumnName(@"Review #")]
            public float Review__ { get; set; }

            [ColumnName(@"Brand")]
            public uint Brand { get; set; }

            [ColumnName(@"Variety")]
            public string Variety { get; set; }

            [ColumnName(@"Style")]
            public string Style { get; set; }

            [ColumnName(@"Country")]
            public string Country { get; set; }

            [ColumnName(@"Stars")]
            public float Stars { get; set; }

            [ColumnName(@"Top Ten")]
            public string Top_Ten { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SampleRecommendation.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
