// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;

namespace SampleRecommendation.ConsoleApp
{
    public partial class SampleRecommendation
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"ISBN",inputColumnName:@"ISBN")      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"User-ID",inputColumnName:@"User-ID"))      
                                    .Append(mlContext.Recommendation().Trainers.MatrixFactorization(new MatrixFactorizationTrainer.Options(){LabelColumnName=@"Book-Rating",MatrixColumnIndexColumnName=@"User-ID",MatrixRowIndexColumnName=@"ISBN",ApproximationRank=20,LearningRate=1,NumberOfIterations=128,Quiet=true}));

            return pipeline;
        }
    }
}
