// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SampleClassification.ConsoleApp
{
    public partial class SampleClassification
    {
        /// <summary>
        /// model input class for SampleClassification.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"class")]
            public string Class { get; set; }

            [ColumnName(@"cap-shape")]
            public string Cap_shape { get; set; }

            [ColumnName(@"cap-color")]
            public string Cap_color { get; set; }

            [ColumnName(@"bruises")]
            public bool Bruises { get; set; }

            [ColumnName(@"odor")]
            public string Odor { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SampleClassification.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"class")]
            public uint Class { get; set; }

            [ColumnName(@"cap-shape")]
            public float[] Cap_shape { get; set; }

            [ColumnName(@"cap-color")]
            public float[] Cap_color { get; set; }

            [ColumnName(@"bruises")]
            public float[] Bruises { get; set; }

            [ColumnName(@"odor")]
            public float[] Odor { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SampleClassification.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
